### ISSUE TITLE
scan examples RNN: mini-batch extension 

### ISSUE THREAD

**Issue by ahmed-touati** [rdipietro/jupyter-notebooks#1]
The code uses only one training example. 
What should I add to perform a mini-batch training?
Coud I use `tensorflow.scan` over batch_size?

**Comment by rdipietro** [comment]
The main change would be to `_vanilla_rnn_step`, where `x` and `h` would end up having one row for each sequence in the batch. (You wouldn't use `scan` over the sequences.)

But there are some other complications too. First you need to figure out how to get multiple sequences of unequal length into the batch. What I do in this scenario is just replicate short sequences in time (by wrapping them around) during training. Second, if you take an approach like this, you have to handle state resets appropriately. What I do is maintain a `reset` `Tensor` and use `tf.cond` with these resets to choose either 1) the initial state, for example all zeros, or 2) the state coming from the previous time step.

I'll post a more realistic version at some point, but the boilerplate code will make it less straightforward than the tensorflow-scan-examples notebook. I'll leave this open until I post it.

**Comment by rdipietro** [comment]
A more complex example with a batch size greater than 1 is [here](https://github.com/rdipietro/miccai-2016-surgical-activity-rec). See `train_and_eval.ipynb`.
