### ISSUE TITLE
Why are the samples assumed to be identically distributed?

### ISSUE THREAD

**Issue by Nitinsiwach** [rdipietro/jupyter-notebooks#3]
I am miles off an understanding here i assume and this is my first time raising an issue on git so please i beg everyone's indulgence
The post makes the point that
>Because we usually assume that our samples are independent and identically distributed, the likelihood over all of our examples decomposes into a product over the likelihoods of individual examples:
L({y(n)},{y^(n)})=∏nL(y(n),y^(n)) 

 (sorry first issue on git, do not know how to math)
Here is what my issue is: 
1. How come the samples are identically distributed? Do we not have actual probability distributions of each sample as 0 for each value except a 1 at the actual label place. For example (from the post): 
>To keep going with this example, let's assume we have a total of four training images, with labels {landscape, something else, landscape, house}, giving us ground-truth distributions  y(1)=(1.0,0.0,0.0)Ty(1)=(1.0,0.0,0.0)T ,  y(2)=(0.0,0.0,1.0)Ty(2)=(0.0,0.0,1.0)T ,  y(3)=(1.0,0.0,0.0)Ty(3)=(1.0,0.0,0.0)T , and  y(4)=(0.0,1.0,0.0)Ty(4)=(0.0,1.0,0.0)T 

so are not y(1), y(2), y(3), y(4) having different distributions? 

2. Is anywhere the identically distributed part needed. Is not the entire mathematics in post consistent with just the independent distributions assumption?

**Comment by rdipietro** [comment]
The independence is over *examples*, whereas I think you're interpreting some sort of independence over labels for a single example. The main idea is that there's no reason to believe that the labels between (say) examples 1 and 2 are dependent, and this assumption is used to maximize the overall likelihood of our dataset, which contains all examples.

Maybe take a look at something like https://stats.stackexchange.com/questions/17391/what-are-i-i-d-random-variables
