### ISSUE TITLE
Possible typo in "A Friendly Introduction to Cross-Entropy Loss"

### ISSUE THREAD

**Issue by johntbates** [rdipietro/jupyter-notebooks#4]
First, thanks for the excellent tutorial!  I've always wondered about the relationship between entropy and cross-entropy loss, and you explained it perfectly.  

I did notice a possible typo in the "Predictive Power" section:

> is just the first entry of  y^(1)=(0.4,0.1,0.5)T , which is y1(1)=0.4 .

Shouldn't that last y1(1) be y^1(1)?

**Comment by rdipietro** [comment]
Thanks for the kind words :). Yes you're right – I'll update
