### ISSUE TITLE
Why in order to get the smallest number of bits we must use the log of probability of occurrence

### ISSUE THREAD

**Issue by octaviantu** [rdipietro/jupyter-notebooks#5]
Hi,

Great article!
I have a question, not sure if it's OK if I post this here as an issue. If it's not I'll delete it.

When talking about encoding elements of a distribution in order to minimise the number of bits, i [your article](https://rdipietro.github.io/friendly-intro-to-cross-entropy-loss/) says this:

*It turns out that if you have access to the underlying distribution y, then to use the smallest number of bits on average, you should assign log(1/y_i) bits to the i-th symbol.*

Why log(1/y_i)?

How can we prove that this is the minimum?

**Comment by rdipietro** [comment]
Thanks! Well, this statement in itself is pretty vague, as emphasis is on intuitions rather than rigor. I'd recommend Googling a bit for Shannon's source coding theorem – it's the more formal version of this statement, and you can find more than one rigorous proof on the web... Hope that helps :).
