### ISSUE TITLE
Distinguishing y and y_hat

### ISSUE THREAD

**Issue by jpeg729** [rdipietro/jupyter-notebooks#6]
I can never remember whether y_hat is supposed to be the target value or the prediction output, which makes skim reading your article quite difficult.

Two possible solutions...
1. Add a position:fixed legend that stays visible.
2. Use clearer names, e.g. `p` for the prediction output, `t` for the true value.

**Comment by rdipietro** [comment]
Hi. Sorry, I disagree here: it's common to add a hat to represent an estimate. And I personally do not like when authors move away from y for predictions / labels, e.g. as done in Bishop's book.
