### ISSUE TITLE
Some questions about notation

### ISSUE THREAD

**Issue by AllanLRH** [rdipietro/jupyter-notebooks#7]
Hi Rob!

I enjoy reading "A Friendly Introduction to Croo-Entropy Loss", but I have a few questions about the notation used, because I don't think that I've come across of it before.

I think the notation is explained well enough in the post, but I'm wondering if it's a standard notation in some fields, and if it is, if you could point me towards a webpage/pdf providing an overview of the notation :)

It's the red parts which is new to me.

<img src="http://latex.codecogs.com/gif.latex?%5Cdpi%7B120%7D%20%24%24%20%5Cmbox%7BKL%7D%28%7B%5Ccolor%7BRed%7D%20y%7E%7C%7C%7E%5Chat%7By%7D%7D%29%20%3D%20%5Csum_i%20y_i%20%5Clog%20%5Cfrac%7B1%7D%7B%5Chat%7By%7D_i%7D%20-%20%5Csum_i%20y_i%20%5Clog%20%5Cfrac%7B1%7D%7By_i%7D%20%3D%20%5Csum_i%20y_i%20%5Clog%20%5Cfrac%7By_i%7D%7B%5Chat%7By%7D_i%7D%20%24%24">

<img src="http://latex.codecogs.com/gif.latex?%5Cdpi%7B120%7D%20%24%24%20H%28%7B%5Ccolor%7BRed%7D%20%5C%7By%5E%7B%28n%29%7D%5C%7D%2C%20%5C%7B%5Chat%7By%7D%5E%7B%28n%29%7D%5C%7D%7D%29%20%3D%20%5Csum_n%20H%28y%5E%7B%28n%29%7D%2C%20%5Chat%7By%7D%5E%7B%28n%29%7D%29%20%24%24">

**Comment by rdipietro** [comment]
Hi Allan,

Thanks!

The KL notation is  common (I assuming you're asking about the ||), but I don't know where the (odd) notation originally comes from. For example take a look at the Wikipedia page on KL divergence.

In the case of cross entropy, I assume you're asking about the set notation? I would guess that it's not standard... just my way of getting the idea across.
